[package]
name = "web-scrapping"
version = "0.1.0"
authors = ["Olivier ROLAND <newca12@users.noreply.github.com>"]
edition = "2021"

[dependencies]
reqwest = "0.11.22"
scraper = "0.18.1"
tokio = { version = "1.33.0", features = ["full"] }