[package]
name = "parsing"
version = "0.1.0"
authors = ["Olivier ROLAND <newca12@users.noreply.github.com>"]
edition = "2021"

[dependencies]
regex = "1.9.4"
nom = "7.1.3"
criterion = "0.5.1"

[profile.dev]
split-debuginfo = "unpacked"

[[bench]]
name = "regex"
harness = false