[package]
name = "antlr-calc"
version = "0.1.0"
authors = ["Olivier ROLAND <newca12@users.noreply.github.com>"]
edition = "2021"

[dependencies]
antlr-rust = "0.3.0-beta"
serde = { version = "1.0.188", features = ["derive"] }
